export const startFieldItems = [
  {
    type: "player",
    step: 0,
    number: "1",
    positionX: 10,
    positionY: 200,
    color: "blue",
  },
  {
    type: "player",
    step: 0,
    number: "2",
    positionX: 70,
    positionY: 200,
    color: "blue",
  },
  {
    type: "player",
    step: 0,
    number: "3",
    positionX: 130,
    positionY: 200,
    color: "blue",
  },
  {
    type: "player",
    step: 0,
    number: "4",
    positionX: 190,
    positionY: 200,
    color: "blue",
  },
  {
    type: "player",
    step: 0,
    number: "5",
    positionX: 250,
    positionY: 200,
    color: "blue",
  },
  {
    type: "player",
    step: 0,
    number: "1",
    positionX: 10,
    positionY: 300,
    color: "red",
  },
  {
    type: "player",
    step: 0,
    number: "2",
    positionX: 70,
    positionY: 300,
    color: "red",
  },
  {
    type: "player",
    step: 0,
    number: "3",
    positionX: 130,
    positionY: 300,
    color: "red",
  },
  {
    type: "player",
    step: 0,
    number: "4",
    positionX: 190,
    positionY: 300,
    color: "red",
  },
  {
    type: "player",
    step: 0,
    number: "5",
    positionX: 250,
    positionY: 300,
    color: "red",
  },
  {
    type: "star",
    step: 0,
    positionX: 100,
    positionY: 60,
  },
  {
    type: "ball",
    step: 0,
    positionX: 40,
    positionY: 60,
  },
];
